# global settings
font pango:monospace 12
blur enable
set $floating floating enable
set $sticky floating enable, sticky enable
set $tiling floating disable, sticky disable
set $rounded corners 10
set $borderless border pixel none
set $center_popup_s resize set width 600, resize set height 480
set $center_popup_m resize set width 800, resize set height 600
set $center_popup_l resize set width 1000, resize set height 800
set $center_popup_xl resize set width 1200, resize set height 1000
set $border border pixel 2
for_window [class=".*" app_id=".*"] $borderless, $floating, opacity 1.0

# settings for specific windows

# tools I want to tile
for_window [app_id="foot"] $tiling, $rounded
for_window [app_id="firefox"] $tiling
for_window [app_id="LibreWolf"] $tiling
for_window [app_id="discord"] $tiling
for_window [app_id="Slack"] $tiling
for_window [app_id="localsend"] $tiling
for_window [title="TILE*"] $tiling
for_window [class="steam"] $tiling
for_window [app_id="org.pwmt.zathura"] $tiling
for_window [class="VirtualBox Machine"] $tiling


for_window [title="Close Virtual Machine"] $borderless, $floating, $border, $center_popup_s
for_window [title="Oracle VirtualBox Manager"] $borderless, $floating, $border, $center_popup_xl
for_window [title="Launching..."] $borderless, $floating, $border, $center_popup_s
