set $w1  '1:  Code'
set $w2  '2:  Code'
set $w3  '3:󰲏 2D'
set $w4  '4:󰂫 3D'
set $w5  '5: Engine'
set $w6  '6: Audio'
set $w7  '7: '
set $w8  '8:󰓓 Games'
set $w9  '9:󰓓 Steam'
set $w0  '10: Scratch'
set $wl1 '1l:󰟐 Info'
set $wl2 '2l: AI'
set $wl3 '3l:󰲏 2D'
set $wl4 '4l:󰲏 3D'
set $wl5 '5l: Engine'
set $wl6 '6l: Audio'
set $wl7 '7l: Rx/Tx'
set $wl8 '8l: Social'
set $wl9 '9l: '
set $wl0 '10l: Scratch'
set $wr1 '1r:  HTML'
set $wr2 '2r:󰈦 PDF'
set $wr3 '3r:󰲏 2D'
set $wr4 '4r:󰲏 3D'
set $wr5 '5r: Engine'
set $wr6 '6r: Audio'
set $wr7 '7r: GPT'
set $wr8 '8r:󰙯 Social'
set $wr9 '9r: '
set $wr0 '10r: Scratch'

workspace $wl1 output $viotek_display
workspace $wl2 output $viotek_display
workspace $wl3 output $viotek_display
workspace $wl4 output $viotek_display
workspace $wl5 output $viotek_display
workspace $wl6 output $viotek_display
workspace $wl7 output $viotek_display
workspace $wl8 output $viotek_display
workspace $wl9 output $viotek_display
workspace $w0 output $gigabyte_display
workspace $w1 output $gigabyte_display
workspace $w2 output $gigabyte_display
workspace $w3 output $gigabyte_display
workspace $w4 output $gigabyte_display
workspace $w5 output $gigabyte_display
workspace $w6 output $gigabyte_display
workspace $w7 output $gigabyte_display
workspace $w8 output $gigabyte_display
workspace $w9 output $gigabyte_display
workspace $wr1 output $msi_display
workspace $wr2 output $msi_display
workspace $wr3 output $msi_display
workspace $wr4 output $msi_display
workspace $wr5 output $msi_display
workspace $wr6 output $msi_display
workspace $wr7 output $msi_display
workspace $wr8 output $msi_display
workspace $wr9 output $msi_display

assign [app_id="LibreWolf"] $wr1
assign [app_id="audacity"] $w6
assign [app_id="blender-*"] $w4
assign [app_id="google-chrome"] $wr1
assign [app_id="librewolf"] $wr1
assign [app_id="localsend"] $wl7
assign [app_id="nvidia-settings"] $w10
assign [app_id="org.pwmt.zathura"] $wr2
assign [class="Gimp-*"] $w3
assign [class="Godot"] $w5
assign [class="REAPER"] $w6
assign [class="Slack"] $wl8
assign [class="discord"] $wr8
assign [class="libresprite"] $wl3
assign [class="steam"] $w9
assign [class="steam_app_*"] $w9
assign [class="t-engine64"] $w9
assign [instance="noi"] $wr7
assign [class="resolve"] $w4
assign [app_id="org.kde.kdenlive"] $w4
assign [class="VirtualBox Machine"] $w6

assign [class=".*w1"] $w1
assign [class=".*w2"] $w2
assign [class=".*w3"] $w3
assign [class=".*w4"] $w4
assign [class=".*w5"] $w5
assign [class=".*w6"] $w6
assign [class=".*w7"] $w7
assign [class=".*w8"] $w8
assign [class=".*w9"] $w9
assign [class=".*w0"] $w0
assign [class=".*wl1"] $wl1
assign [class=".*wl2"] $wl2
assign [class=".*wl3"] $wl3
assign [class=".*wl4"] $wl4
assign [class=".*wl5"] $wl5
assign [class=".*wl6"] $wl6
assign [class=".*wl7"] $wl7
assign [class=".*wl8"] $wl8
assign [class=".*wl9"] $wl9
assign [class=".*wl0"] $wl0
assign [class=".*wr1"] $wr1
assign [class=".*wr2"] $wr2
assign [class=".*wr3"] $wr3
assign [class=".*wr4"] $wr4
assign [class=".*wr5"] $wr5
assign [class=".*wr6"] $wr6
assign [class=".*wr7"] $wr7
assign [class=".*wr8"] $wr8
assign [class=".*wr9"] $wr9
assign [class=".*wr0"] $wr0

